Medical-Store-Management-System-main/MedicalStore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls'))
]

Medical-Store-Management-System-main/store/urls.py
from django.urls import path
from store import views

app_name = 'store'
urlpatterns = [
    path('', views.index, name='store-home'),
    path('register/staff/', views.staff_register, name='staff-register'),
    path('register/bill/', views.bill_register, name='bill-register'),
    path('register/stock/', views.stock_register, name='stock-register'),
    path('register/medicine/', views.medicine_register, name='medicine-register'),
    path('register/supplier', views.supplier_register, name='supplier-register'),
    path('staff/all/', views.staff_all, name='staff-all'),
    path('staff/delete/<int:pk>/', views.staff_delete, name='staff-delete'),
    path('staff/update/<int:pk>/', views.staff_update, name='staff-update'),
    path('medicine/all/', views.medicine_all, name='medicine-all'),
    path('medicine/delete/<int:pk>/', views.medicine_delete, name='medicine-delete'),
    path('medicine/update/<int:pk>/', views.medicine_update, name='medicine-update'),
    path('supplier/all/', views.supplier_all, name='supplier-all'),
    path('supplier/delete/<int:pk>/', views.supplier_delete, name='supplier-delete'),
    path('supplier/update/<int:pk>/', views.supplier_update, name='supplier-update'),
    path('developers/', views.info, name='info'),
    path('bill/all/', views.bill_all, name='bill-all'),
    path('stock/all/', views.stock_all, name='stock-all'),
    path('stock/sort/medicine/', views.stock_med_sort, name='stock-med-sort')
]

Medical-Store-Management-System-main/store/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):
	emp_name = models.CharField(max_length=100)
	emp_gender = models.CharField(max_length=100, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')])
	emp_age = models.PositiveIntegerField()
	emp_salary = models.PositiveIntegerField()

	def __str__(self):
		return self.emp_name
	

Medical-Store-Management-System-main/store/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponse
import datetime

import mysql.connector

try:
	conn = mysql.connector.connect(host="localhost", user="username", password="password", database='your_database', auth_plugin='mysql_native_password')
	print("Connected to MySQL Database")
except:
	print("Can't Connect to MySQL Database")

cur = conn.cursor()


def info(request):
	return render(request, 'store/info.html')


def index(request):
	try:
		params = []
		query = "SELECT COUNT(emp_id) FROM employee"
		cur.execute(query)
		count_of_employee = int(cur.fetchall()[0][0])
		params.append(count_of_employee)

		query = "SELECT exp_date from stock"
		cur.execute(query)
		result = cur.fetchall()
		count = 0

		for date in result:
			days = (date[0] - datetime.date.today()).days
			if days <= 30:
				count = count + 1
		params.append(count)

		query = "select distinct(med_name) from medicine natural join stock;"
		cur.execute(query)
		res = cur.fetchall()
		params.append(res)

		d = datetime.date.today()
		full_date = str(d.year) + '-' +str(d.month) + '-' + str(d.day)
		query=f"select sum(price) from bill where bill_date = '{full_date}'"
		cur.execute(query)
		res = cur.fetchall()
		params.append(res[0][0])
		
		return render(request, 'store/index.html', {'params': params})

	except Exception as e:
		print(e)
		return render(request, 'store/index.html', {'params': [0,0]})


def bill_all(request):
	query = 'select * from bill order by bill_date desc;'
	try:
		cur.execute(query)
		records = cur.fetchall()
	except:
		messages.error(request, "Some Error Occurred !")
		return redirect('store:store-home')
	return render(request, 'store/bill_all.html', {'records':records})


# BILL
def bill_register(request):

	if request.method=='POST':
		value = []
		customername = request.POST.getlist('name')[0]
		medname = request.POST.getlist('medicine')
		qua = request.POST.getlist('quantity')
		d = datetime.date.today()
		full_date = str(d.year) + '-' +str(d.month) + '-' + str(d.day)
		try:
			for i in range(len(medname)):
				query = f"select sum(curr_quantity) from medicine natural join stock where med_name='{medname[i]}' group by med_name;"
				cur.execute(query)
				data = cur.fetchone()[0]
				if data < int(qua[i]):
					messages.error(request, f"Sorry, Required Quantity Of   \"{medname[i]}\"   Not Available !")
					return redirect('store:store-home') 	

			for name in request.POST.getlist('medicine'):
				query=f"SELECT med_price FROM medicine where med_name=\'{name}\'"
				cur.execute(query)
				res = cur.fetchall()
				value.append(res[0][0])
			
			count = 0
			for q in request.POST.getlist('quantity'):
				value[count] *= int(q)
				count = count + 1
			
			for i in range(len(value)):
				query=f"INSERT INTO bill (cust_name, med_name, quantity, price, bill_date) VALUES (\'{customername}\', \'{medname[i]}\', {qua[i]}, {value[i]}, '{full_date}')"
				cur.execute(query)
				conn.commit()
				
				query_2 = f"select * from stock where med_id in (select med_id from medicine where med_name='{medname[i]}') and curr_quantity > 0 order by exp_date;"
				cur.execute(query_2)
				records = cur.fetchall()
				quantities = []
				item_quantity = int(qua[i])
				
				for record in records:
					quantities.append([record[0],record[8]])

				total_quantity = 0
				
				for i in quantities:
					total_quantity += i[1]
				
				if item_quantity > total_quantity:
					messages.error(request, "Not Sufficient Quantity")
					return redirect('store:store-home')
				
				for i in quantities:
					if item_quantity > i[1]:
						item_quantity = item_quantity - i[1]
						i[1] = 0
					else:
						i[1] = i[1] - item_quantity
				
				for i in quantities:
					query = f"update stock set curr_quantity = {i[1]} where stock_id = {i[0]};"
					cur.execute(query)
					conn.commit()

			messages.success(request, "Bill Generated Successfully !")
				
			return redirect("store:store-home")
		except Exception as e:
			print("**\n",e,"\n**")
			messages.error(request, "Some Error Occurred !")
			return redirect('store:store-home')


	return render(request, 'store/index.html')


# STAFF
def staff_register(request):

	if request.method == 'POST':
		name = request.POST['firstname'] + " " + request.POST['lastname']
		gender = request.POST['gender']
		age = int(request.POST['age'])
		salary = int(request.POST['salary'])
		# Write in database
		query = f"insert into employee (emp_name, emp_gender, emp_age, emp_salary) values ('{name}','{gender}',{age},{salary});"
		try:
			cur.execute(query)
			conn.commit()
		except:
			messages.error(request,"Some Error Occured !")
			return redirect('store:staff-all')

		messages.success(request, 'Record Saved Successfully !')
		return redirect('store:staff-all')
	else:
		pass
	return render(request, 'store/staff_form.html')


def staff_all(request):

	cur.execute('select * from employee;')
	records = cur.fetchall()
	return render(request, 'store/staff_all.html', {'records':records})


def staff_delete(request, pk):

	try:
		query = f'delete from employee where emp_id={pk}'
		cur.execute(query)
		conn.commit()
		messages.success(request, "Record Deleted Successfully !")
	except:
		messages.error(request, "Can't Delete Record !")
	return redirect('store:staff-all')


def staff_update(request, pk):
	
	query = f'select * from employee where emp_id={pk}'
	try:
		cur.execute(query)
		val = cur.fetchone()
	except:
		messages.error(request, "Can't Update Record !")
		return redirect('store:staff-all')
	emp={
		'emp_id':val[0],
		'fname':val[1].split()[0],
		'lname':val[1].split()[1],
		'gender':val[2],
		'age':val[3],
		'salary':val[4]
	}
	if request.method == 'POST':
		emp_id = request.POST['emp_id'] 
		name = request.POST['firstname'] + " " + request.POST['lastname']
		gender = request.POST['gender']
		age = int(request.POST['age'])
		salary = int(request.POST['salary'])
		query = f"update employee set emp_name = '{name}', emp_gender = '{gender}', emp_age = {age}, emp_salary = {salary} where emp_id = {emp_id};"	
		cur.execute(query)
		conn.commit()
		messages.success(request, "Record Updated Successfully !")
		return redirect('store:staff-all')

	return render(request, 'store/staff_update.html',{'emp':emp})

# STOCK
def stock_register(request):
	try:
		medicines = []
		suppliers = []
		query = 'select med_name from medicine order by med_name'
		cur.execute(query)
		med_items = cur.fetchall()
		for item in med_items:
			medicines.append(item[0])
		
		query = 'select supplier_name from supplier order by supplier_name'
		cur.execute(query)
		supp_items = cur.fetchall()
		for item in supp_items:
			suppliers.append(item[0])
		
	except:
		messages.error(request, "Some Error Occurred !")
		return redirect('store:stock-register')

	if request.method=='POST':
		medname = request.POST['name']
		quantity = request.POST['quantity']
		price = request.POST['price']
		supplier = request.POST['supplier']
		mfg_date = request.POST['mfg_date']
		exp_date = request.POST['exp_date']
		d = datetime.date.today()
		arr_date = str(d.year) + '-' +str(d.month) + '-' + str(d.day)
		try:
			query = f"SELECT med_id FROM medicine WHERE med_name=\'{medname}\'"
			cur.execute(query)
			medid = cur.fetchall()[0][0]
		except:
			messages.error(request, "Medicine Not Registered ! Please Register First From /register/medicine .")
			return redirect("store:stock-all")
			
		try:
			query = f"SELECT supplier_id FROM supplier WHERE supplier_name=\'{supplier}\'"
			cur.execute(query)
			supid=cur.fetchall()[0][0]
		except:
			messages.error(request, "Supplier Not Registered ! Please Register First From /register/supplier .")
			return redirect("store:supplier-register")
						
		query = f"INSERT INTO stock (quantity, price, mfg_date, exp_date, stock_arrival_date, supplier_id, med_id, curr_quantity) VALUES ({quantity}, {price}, \'{mfg_date}\', \'{exp_date}\', \'{arr_date}\', {supid}, {medid}, {quantity})"
		cur.execute(query)
		conn.commit()
		messages.success(request, "Record Registered Successfully !")
		return redirect("store:stock-all")
	else:
		return render(request, 'store/stock_form.html', {'medicines':medicines, 'suppliers':suppliers})


def stock_med_sort(request):
	query = 'select med_name, sum(quantity),sum(curr_quantity) from stock natural join medicine group by med_id order by med_name;'
	try:
		cur.execute(query)
		records = cur.fetchall()
	except:
		messages.error(request, "Some Error Occurred!")
		return redirect('store:stock-all')

	return render(request, 'store/stock_med_sort.html', {'records':records})


def stock_all(request):
	try:
		cur.execute('select stock_id, quantity, price, mfg_date, exp_date, stock_arrival_date, med_name, supplier_name, curr_quantity from stock natural join medicine natural join supplier order by exp_date;')
		records = cur.fetchall()
	except:
		messages.error(request, "Some Error Occurred !")
		return redirect('store:stock-all')
	
	return render(request, 'store/stock_all.html', {'records':records})


# SUPPLIER
def supplier_register(request):

	if request.method == 'POST':
		suppliername = request.POST["supname"]
		city = request.POST["city"]			
		pincode = request.POST["pincode"]
		query = f"INSERT INTO supplier (supplier_name, supplier_city, city_pincode) VALUES ('{suppliername}', '{city}', {pincode});"
		print(query)
		try:
			cur.execute(query)
			conn.commit()
			messages.success(request, "Record Saved Successfully !")
			return redirect('store:supplier-all')
		except:
			messages.error(request, "Some Error Occurred !")
			return redirect('store:supplier-all')
			
	else:
		return render(request, 'store/supplier_form.html')


def supplier_all(request):
	query = 'select * from supplier;'
	try:
		cur.execute(query)
		records = cur.fetchall()
	except:
		messages.error(request, "Some Error Occurred !")
		return redirect('store:supplier-all')
	
	return render(request, 'store/supplier_all.html', {'records':records})


def supplier_delete(request, pk):

Medical-Store-Management-System-main/store/templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Medical Store Management</title>

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static 'store/style.css' %}">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>

</head>

<body>

    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>Medical Management System</h3>
                <strong>MM</strong>
            </div>

            <ul class="list-unstyled components">
                <li>
                    <a href="{% url 'store:store-home' %}">
                        <i class="fas fa-home"></i>
                        Home
                    </a>
                </li>
                <li>
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="fas fa-briefcase"></i>
                        Manage Stock
                    </a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="{% url 'store:stock-register' %}">Add</a>
                        </li>
                        <li>
                            <a href="{% url 'store:stock-all' %}">View All</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="fas fa-copy"></i>
                        Staff
                    </a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href={% url 'store:staff-register' %}>Register</a>
                        </li>
                        <li>
                            <a href={% url 'store:staff-all' %}>View All</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#medSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="fas fa-medkit" aria-hidden="true"></i>
                        Medicines
                    </a>
                    <ul class="collapse list-unstyled" id="medSubmenu">
                        <li>
                            <a href="{% url 'store:medicine-register' %}">Add</a>
                        </li>
                        <li>
                            <a href="{% url 'store:medicine-all' %}">View All</a>
                        </li>
                    </ul>
                </li>                
                <li>
                    <a href="#supSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="fas fa-medkit" aria-hidden="true"></i>
                        Supplier
                    </a>
                    <ul class="collapse list-unstyled" id="supSubmenu">
                        <li>
                            <a href="{% url 'store:supplier-register' %}">Add</a>
                        </li>
                        <li>
                            <a href="{% url 'store:supplier-all' %}">View All</a>
                        </li>
                    </ul>
                </li>                
                <li>
                    <a href="{% url 'store:info' %}">
                        <i class="fas fa-image"></i>
                        Developers
                    </a>
                </li>
                <li>
                    <a href="{% url 'store:bill-all' %}">
                        <i class="fas fa-question"></i>
                        All Bills
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-paper-plane"></i>
                        Contact
                    </a>
                </li>
            </ul>
        </nav>

        <!-- Page Content  -->
        <div id="content">

            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-light">
                        <i class="fas fa-align-left"></i>
                        <span>Toggle Sidebar</span>
                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="/admin">Admin</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="container">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                            <strong>Message: </strong>{{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>

            {% block content %}
                
            {% endblock content %}
        
        </div>
    </div>

    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });

        $(document).ready(function() {
            var max_fields      = 10; //maximum input boxes allowed
            var wrapper   		= $(".input_fields_wrap"); //Fields wrapper
            var add_button      = $("#add_field_button"); //Add button ID
            
            var x = 1; //initlal text box count
            $(add_button).click(function(e){ //on add input button click
                e.preventDefault();
                if(x < max_fields){ //max input box allowed
                    x++; //text box increment
                    $(wrapper).append('<div class="input_fields_wrap"><div class="form-row"><div class="form-group col-md-6"><select id="selectMedicine" class="form-control" name="medicine">{% for med in params.2 %}<option value={{ med.0 }}>{{ med.0 }}</option>{% endfor %}  </select></div><div class="form-group col-md-4"><input type="number" class="form-control" id="quantity" placeholder="Enter Quantity" name="quantity"></div><div class="form-group col-md-2"><a role="button" class="btn btn-danger" id="remove_field">Remove</a></div></div></div>');
                }
            });
            
            $(wrapper).on("click","#remove_field", function(e){ //user click on remove text
                e.preventDefault(); $(this).parent('div').parent('div').remove(); x--;
            })
        });
    </script>
</body>

</html>

Medical-Store-Management-System-main/store/templates/store/medicine_all.html
{% extends 'store/base.html' %}
{% block content %}

<div class= "container my-4 py-4">
    <h2>All Medicines</h2><hr>
    <table class="table table-striped table-hover">
        <thead class="thead-dark">
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Price/Quantity</th>
            <th scope="col">Update</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
            {% for record in records %}
            <tr>
                <th scope="row"> {{record.0}} </th>
                <td> {{record.1}} </td>
                <td> Rs. {{record.2}} </td>
                <td><a role="button" href="{% url 'store:medicine-update' pk=record.0 %}" class="btn btn-success">Update</a></td>
                <td><a role="button" href="{% url 'store:medicine-delete' pk=record.0 %}" class="btn btn-danger">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <hr>
    <center>
        <a style="align:center" href={% url 'store:medicine-register' %} role="button" class="btn btn-info btn-lg col-md-2">Add</a>
    </center>
<div>
{% endblock content %}

Medical-Store-Management-System-main/store/templates/store/medicine_update.html
{% extends 'store/base.html' %}
{% block content %}
    <div class="container">
      
      <form action="{% url 'store:medicine-update' pk=med.0 %}" method="POST" class="col-md-10">
      <h2>Medicine Entry Form</h2><hr>
        {% csrf_token %}
        <div class="form-group">
            <h4>Medicine Name:</h4>
            <input type="text" class="form-control"  placeholder="{{ med.1 }}" name="medname" required>
        </div>
        <div class="form-group">
            <h4>Price:</h4>
            <input type="number" class="form-control" placeholder="{{ med.2 }}" name="medprice" required>
        </div>
        <hr>
        <center>
        <button type="submit" class="btn btn-primary col-md-2">Submit</button>
        </center>
      </form>
    </div>
{% endblock content %}
  

Medical-Store-Management-System-main/store/templates/store/staff_all.html
{% extends 'store/base.html' %}
{% block content %}

<div class= "container my-4 py-4">

    <h2>Staff Record</h2><hr>

    <table class="table table-striped table-hover">
        <thead class="thead-dark">
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Gender</th>
            <th scope="col">Age</th>
            <th scope="col">Salary</th>
            <th scope="col">Update</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
            {% for record in records %}
            <tr>
                <th scope="row"> {{record.0}} </th>
                <td> {{record.1}} </td>
                <td> {{record.2}} </td>
                <td> {{record.3}} </td>
                <td> {{record.4}} </td>
                <td><a role="button" href={% url 'store:staff-update' pk=record.0 %} class="btn btn-success">Update</a></td>
                <td><a role="button" href={% url 'store:staff-delete' pk=record.0 %} class="btn btn-danger">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <hr>
    <center>
        <a style="align:center" href={% url 'store:staff-register' %} role="button" class="btn btn-info btn-lg col-md-2">Add</a>
    </center>
    <hr>
</div>

{% endblock content %}

Medical-Store-Management-System-main/store/templates/store/staff_form.html
{% extends 'store/base.html' %}
{% block content %}
    <div class= "container jumbotron p-4">
      <h3>Staff Registration Form</h3><hr>  
      <form action="{% url 'store:staff-register' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="firstname" class="lead">First Name:</label>
            <input type="text" class="form-control"  id="firstnane" placeholder="Enter first name" name="firstname" required>
        </div>
        <div class="form-group">
            <label for="lastname" class="lead">Last Name:</label>
            <input type="text" class="form-control"  id="lastname" placeholder="Enter last name" name="lastname" required>
        </div>
        <div class="form-group">
            <label for="gender" class="lead">Gender:</label>
            <select class="form-group" id="gender" name="gender"  required>
            <option value="male">Male</option>
            <option value="female">Female</option>
            <option value="other">Prefer not to say</option>
            </select>
        <div class="form-group">
            <label for="age" class="lead">Age:</label>
            <input type="number" class="form-control"  id="age" placeholder="Enter age" name="age">
        </div>
        <div class="form-group">
            <label for="salary" class="lead">Salary:</label>
            <input type="number" class="form-control"  id="salary" placeholder="Monthly Salary Rs." name="salary" required>
        </div>
        </div>
        <hr>
        <center>
            <button type="submit" class="btn btn-primary btn-lg col-md-2">Submit</button>
        </center>
      </form>
    </div>
{% endblock content %}
  

Medical-Store-Management-System-main/store/templates/store/staff_update.html
{% extends 'store/base.html' %}
{% block content %}
    <div class= "container jumbotron p-4">
      <h3>Staff Registration Form</h3><hr>  
      <form action="{% url 'store:staff-update' pk=emp.emp_id %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="emp_id" value="{{emp.emp_id}}">
        <div class="form-group">
            <label for="firstname" class="lead">First Name:</label>
            <input type="text" class="form-control" id="firstnane" placeholder="{{emp.fname}}" name="firstname" required>
        </div>
        <div class="form-group">
            <label for="lastname" class="lead">Last Name:</label>
            <input type="text" class="form-control" id="lastname" placeholder="{{emp.lname}}" name="lastname" required>
        </div>
        <div class="form-group">
            <label for="gender" class="lead">Gender:</label>
            <select class="form-group" id="gender" name="gender" required>
            <option value="male">Male</option>
            <option value="female">Female</option>
            <option value="other">Prefer not to say</option>
            </select>
        <div class="form-group">
            <label for="age" class="lead">Age:</label>
            <input type="number" class="form-control" id="age" placeholder="{{emp.age}}" name="age">
        </div>
        <div class="form-group">
            <label for="salary" class="lead">Salary:</label>
            <input type="number" class="form-control" id="salary" placeholder="{{emp.salary}}" name="salary" required>
        </div>
        </div>
        <hr>
        <center>
            <button type="submit" class="btn btn-primary btn-lg col-md-2">Submit</button>
        </center>
      </form>
    </div>
{% endblock content %}
  

Medical-Store-Management-System-main/store/templates/store/supplier_all.html
{% extends 'store/base.html' %}
{% block content %}

<div class= "container my-4 py-4">

    <h2>Supplier Record</h2><hr>

    <table class="table table-striped table-hover">
        <thead class="thead-dark">
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">City</th>
            <th scope="col">Pincode</th>
            <th scope="col">Update</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
            {% for record in records %}
            <tr>
                <th scope="row"> {{record.0}} </th>
                <td> {{record.1}} </td>
                <td> {{record.2}} </td>
                <td> {{record.3}} </td>
                <td><a role="button" href="{% url 'store:supplier-update' pk=record.0 %}" class="btn btn-success">Update</a></td>
                <td><a role="button" href="{% url 'store:supplier-delete' pk=record.0 %}" class="btn btn-danger">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <hr>
    <center>
        <a style="align:center" href="{% url 'store:supplier-register' %}" role="button" class="btn btn-info btn-lg col-md-2">Add</a>
    </center>
    <hr>
</div>

{% endblock content %}